export const ALL_LANGUAGES = {
  'zh-CN': '简体中文 (zh-CN)',
  'zh-TW': '繁體中文 (zh-TW)',
  'ja-JP': '日本語 (ja-JP)',
  'ko-KR': '한국어 (ko-KR)',
  'fr-FR': 'Français (fr-FR)',
  'de-DE': 'Deutsch (de-DE)',
  'es-ES': 'Español (es-ES)',
  'it-IT': 'Italiano (it-IT)',
  'pt-BR': 'Português (pt-BR)',
  'pt-PT': 'Português (pt-PT)',
  'nl-NL': 'Nederlands (nl-NL)',
  'pl-PL': 'Polski (pl-PL)',
  'sv-SE': 'Svenska (sv-SE)',
  'da-DK': 'Dansk (da-DK)',
  'fi-FI': 'Suomi (fi-FI)',
  'nb-NO': 'Norsk (nb-NO)',
  'cs-CZ': 'Čeština (cs-CZ)',
  'sk-SK': 'Slovenčina (sk-SK)',
  'ro-RO': 'Română (ro-RO)',
  'hu-HU': 'Magyar (hu-HU)',
  'el-GR': 'Ελληνικά (el-GR)',
  'bg-BG': 'Български (bg-BG)',
  'uk-UA': 'Українська (uk-UA)',
  'ru-RU': 'Русский (ru-RU)',
  'lt-LT': 'Lietuvių (lt-LT)',
  'lv-LV': 'Latviešu (lv-LV)',
  'et-EE': 'Eesti (et-EE)',
  'tr-TR': 'Türkçe (tr-TR)',
  'vi-VN': 'Tiếng Việt (vi-VN)',
  'th-TH': 'ภาษาไทย (th-TH)',
  'id-ID': 'Bahasa Indonesia (id-ID)',
  'ms-MY': 'Bahasa Melayu (ms-MY)',
  'hi-IN': 'हिन्दी (hi-IN)',
};
